### ISSUE TITLE
PHP 8 requirement

### ISSUE THREAD

**Issue by amcates** [susom/OnCore-Integration#228]
Just curious why this has a PHP 8 requirement.  Our instance of REDCap runs on 7.4.33 and we would like to use this module.   If it's only because of available testing platforms then I understand and we would be happy to test it against our installed version of PHP.

**Comment by ihabzee** [comment]
Hi @amcates,

Thanks for reaching out. The main reason we added this requirement is that PHP 7 is no longer supported. And we did not have the manpower to test the EM against older versions of PHP. If you want to test it against PHP 7.4 then we can drop PHP version requirements if no issues are caused by PHP 7.

**Comment by amcates** [comment]
@ihabzee Thanks for the quick response.  I'll see if I can get our team to test it on 7.4.

**Comment by AndrewPoppe** [comment]
@ihabzee I was wondering what came of this? Is there a set of tests that would be required for you to see in order to drop the PHP 8 requirement? I'm doing informal testing right now, and it seems to be working just fine in PHP 7.4 (outside of a few things that I will bring up in a separate issue - I don't think they're PHP 8 related).
